"""Marginal Impact Engine for AllocateAI Decision Engine (Member C Phase 4).

Estimates additional social impact generated by an incremental CSR investment.
Answers: "If AllocateAI invests one more ₹1 lakh into this project, how much additional impact is created?"
Authoritative source: Software Contract v1.0 & Technical Contract v1.0.
Strictly deterministic: zero LLM calls, zero randomness, zero external APIs, zero database calls.
All monetary amounts represented in integer paise.
"""

from typing import Any, Final

from backend.app.engine.constants import (
    DEFAULT_MARGINAL_INCREMENT_PAISE,
    DNA_SCHEMA_VERSION,
    MARGINAL_CALCULATION_VERSION,
    PAISE_PER_LAKH,
    SCORE_MAX,
    SCORE_MIN,
)
from backend.app.engine.exceptions import (
    BudgetValidationError,
    InvalidProjectDataError,
)
from backend.app.engine.schemas import (
    ImpactDNA,
    MarginalImpactResult,
    Project,
    SaturationResult,
)
from backend.app.engine.utils import (
    clip_score,
    safe_division,
    validate_paise,
    validate_score,
)

# ---------------------------------------------------------------------------
# Version & Algorithm Constants (Task G)
# ---------------------------------------------------------------------------

CALCULATION_VERSION: Final[str] = MARGINAL_CALCULATION_VERSION  # "marginal-v1"
ENGINE_VERSION: Final[str] = "marginal-impact-engine"
INPUT_SCHEMA: Final[str] = DNA_SCHEMA_VERSION                   # "dna-v1"

DEPENDENCY_VERSIONS: Final[dict[str, str]] = {
    "scoring": "scoring-v1",
    "saturation": "saturation-v1",
}

DEFAULT_MARGINAL_PRECISION: Final[int] = 6

# Canonical weights for marginal impact score combination (Task F)
# Sum strictly equals 1.0
COST_EFFICIENCY_WEIGHT: Final[float] = 0.40
NEED_BONUS_WEIGHT: Final[float] = 0.35
SATURATION_PENALTY_WEIGHT: Final[float] = 0.25

# Standard incremental tiers for simulation (in integer paise)
SIMULATION_TIERS: Final[dict[str, int]] = {
    "1L": 1 * PAISE_PER_LAKH,   # 10,000,000 paise (₹1 lakh)
    "2L": 2 * PAISE_PER_LAKH,   # 20,000,000 paise (₹2 lakh)
    "5L": 5 * PAISE_PER_LAKH,   # 50,000,000 paise (₹5 lakh)
    "10L": 10 * PAISE_PER_LAKH, # 100,000,000 paise (₹10 lakh)
}


class MarginalImpactEngine:
    """Deterministic Marginal Impact Engine for incremental investment evaluation."""

    calculation_version: Final[str] = CALCULATION_VERSION
    engine_version: Final[str] = ENGINE_VERSION
    input_schema: Final[str] = INPUT_SCHEMA
    dependency_versions: Final[dict[str, str]] = DEPENDENCY_VERSIONS

    def __init__(self, precision: int = DEFAULT_MARGINAL_PRECISION) -> None:
        """Initialize the Marginal Impact Engine.

        Args:
            precision: Rounding decimal places (default: 6).
        """
        self.precision = precision

    # -----------------------------------------------------------------------
    # Task A: Public Method - validate_inputs
    # -----------------------------------------------------------------------

    def validate_inputs(
        self,
        project: Project,
        saturation_result: SaturationResult | None = None,
        increment_paise: int | None = None,
    ) -> None:
        """Validate candidate project, optional saturation result, and incremental budget.

        Args:
            project: Candidate project entity with ImpactDNA.
            saturation_result: Optional precomputed SaturationResult.
            increment_paise: Proposed incremental budget in integer paise (> 0).

        Raises:
            InvalidProjectDataError: If project or DNA is invalid or missing.
            BudgetValidationError: If increment is non-integer, negative, or zero.
        """
        if not isinstance(project, Project):
            raise InvalidProjectDataError(
                f"project must be an instance of Project, got {type(project).__name__}"
            )

        dna = getattr(project, "impact_dna", None)
        if dna is None or not isinstance(dna, ImpactDNA):
            raise InvalidProjectDataError(
                f"Project '{project.project_id}' is missing required ImpactDNA fingerprint",
                project_id=project.project_id,
                field_name="impact_dna",
            )

        # Validate core DNA scores
        validate_score(dna.cost_efficiency_score, name="cost_efficiency_score")
        validate_score(dna.need_score, name="need_score")

        if dna.estimated_impact_per_lakh < 0.0:
            raise InvalidProjectDataError(
                f"estimated_impact_per_lakh must be non-negative, got {dna.estimated_impact_per_lakh}",
                project_id=project.project_id,
                field_name="estimated_impact_per_lakh",
            )

        # Validate saturation result if provided
        if saturation_result is not None:
            if not isinstance(saturation_result, SaturationResult):
                raise InvalidProjectDataError(
                    f"saturation_result must be a SaturationResult instance, got {type(saturation_result).__name__}"
                )
            validate_score(saturation_result.saturation_index, name="saturation_index")

        # Validate increment if provided
        if increment_paise is not None:
            validate_paise(increment_paise, name="increment_paise", allow_zero=False)

    # -----------------------------------------------------------------------
    # Task C: Public Method - calculate_diminishing_return
    # -----------------------------------------------------------------------

    def calculate_diminishing_return(
        self,
        project: Project,
        saturation_result: SaturationResult | None,
        projected_budget_paise: int,
    ) -> float:
        """Calculate deterministic diminishing-return factor in range [0.0, 1.0].

        The curve enforces three economic principles:
            1. Absorptive Capacity Decay: As projected budget increases relative to requested
               capacity, marginal efficiency monotonically decreases.
            2. Regional Saturation Penalty: Highly saturated intervention environments experience
               steeper marginal efficiency loss.
            3. Need Preservation: High-need, underserved interventions retain higher efficiency.

        Formula:
            base_decay = 1.0 / (1.0 + 0.50 * (projected_budget / requested_budget))
            saturation_factor = 1.0 - 0.35 * saturation_index
            need_factor = 0.80 + 0.20 * need_score
            diminishing_return_factor = clip(base_decay * saturation_factor * need_factor, 0.0, 1.0)

        Args:
            project: Project entity.
            saturation_result: Regional SaturationResult or None.
            projected_budget_paise: Cumulative budget in integer paise.

        Returns:
            Diminishing return multiplier in [0.0, 1.0].
        """
        requested_paise = project.financials.requested_amount_paise
        budget_ratio = safe_division(
            float(projected_budget_paise),
            float(requested_paise),
            default=1.0,
        )

        # 1. Absorptive capacity decay (strictly monotonically decreasing in budget)
        base_decay = 1.0 / (1.0 + 0.50 * budget_ratio)

        # 2. Regional saturation factor (higher saturation reduces efficiency)
        sat_index = 0.0
        if saturation_result is not None:
            sat_index = saturation_result.saturation_index
        saturation_factor = 1.0 - 0.35 * sat_index

        # 3. Need preservation factor (higher need retains efficiency)
        need_score = 0.50
        if project.impact_dna is not None:
            need_score = project.impact_dna.need_score
        need_factor = 0.80 + 0.20 * need_score

        raw_factor = base_decay * saturation_factor * need_factor
        clipped = clip_score(raw_factor, min_val=SCORE_MIN, max_val=SCORE_MAX)
        return round(clipped, self.precision)

    # -----------------------------------------------------------------------
    # Task B & D: Primary Calculation Method
    # -----------------------------------------------------------------------

    def calculate_marginal_impact(
        self,
        project: Project,
        saturation_result: SaturationResult | None = None,
        increment_paise: int | None = None,
    ) -> MarginalImpactResult:
        """Calculate the incremental impact and marginal score of an additional investment.

        Args:
            project: Candidate project with ImpactDNA.
            saturation_result: Optional precomputed SaturationResult.
            increment_paise: Incremental budget step (default: 10,000,000 paise = ₹1 lakh).

        Returns:
            Validated MarginalImpactResult instance with explainability metadata.
        """
        step_paise = increment_paise if increment_paise is not None else DEFAULT_MARGINAL_INCREMENT_PAISE
        self.validate_inputs(project, saturation_result, step_paise)

        dna = project.impact_dna
        assert dna is not None  # Guaranteed by validate_inputs

        baseline_budget_paise = project.financials.current_funding_paise
        projected_budget_paise = baseline_budget_paise + step_paise

        baseline_budget_lakh = float(baseline_budget_paise) / float(PAISE_PER_LAKH)
        increment_lakh = float(step_paise) / float(PAISE_PER_LAKH)

        impact_rate = dna.estimated_impact_per_lakh
        baseline_impact = impact_rate * baseline_budget_lakh

        # Calculate diminishing return factor
        diminishing_factor = self.calculate_diminishing_return(
            project=project,
            saturation_result=saturation_result,
            projected_budget_paise=projected_budget_paise,
        )

        # Compute incremental and projected impact
        effective_rate_per_lakh = impact_rate * diminishing_factor
        incremental_impact = effective_rate_per_lakh * increment_lakh
        projected_impact = baseline_impact + incremental_impact

        # Calculate calibrated Marginal Impact Score
        cost_eff = dna.cost_efficiency_score
        need_sc = dna.need_score
        sat_idx = saturation_result.saturation_index if saturation_result else 0.0

        # Explainability components
        need_bonus = round(need_sc, self.precision)
        saturation_penalty = round(sat_idx, self.precision)

        # Potential score combines efficiency, need bonus, and saturation headroom
        effective_potential = (
            COST_EFFICIENCY_WEIGHT * cost_eff
            + NEED_BONUS_WEIGHT * need_sc
            + SATURATION_PENALTY_WEIGHT * (1.0 - sat_idx)
        )

        raw_score = diminishing_factor * effective_potential
        marginal_impact_score = round(
            clip_score(raw_score, min_val=SCORE_MIN, max_val=SCORE_MAX),
            self.precision,
        )

        # Build explainability component breakdown (Task F)
        component_breakdown = {
            "baseline_impact": round(baseline_impact, self.precision),
            "projected_impact": round(projected_impact, self.precision),
            "incremental_impact": round(incremental_impact, self.precision),
            "impact_per_lakh": round(effective_rate_per_lakh, self.precision),
            "diminishing_return_factor": diminishing_factor,
            "saturation_penalty": saturation_penalty,
            "need_bonus": need_bonus,
        }

        weights_used = {
            "need_bonus_weight": NEED_BONUS_WEIGHT,
            "saturation_penalty_weight": SATURATION_PENALTY_WEIGHT,
            "cost_efficiency_weight": COST_EFFICIENCY_WEIGHT,
        }

        # Build allocation context metadata (Section G)
        budget_ratio = safe_division(
            float(projected_budget_paise),
            float(project.financials.requested_amount_paise),
            default=1.0,
        )
        allocation_context = {
            "baseline_budget_lakh": round(baseline_budget_lakh, self.precision),
            "projected_budget_lakh": round(float(projected_budget_paise) / float(PAISE_PER_LAKH), self.precision),
            "increment_lakh": round(increment_lakh, self.precision),
            "budget_ratio": round(budget_ratio, self.precision),
        }

        return MarginalImpactResult(
            project_id=project.project_id,
            increment_paise=step_paise,
            baseline_budget_paise=baseline_budget_paise,
            projected_budget_paise=projected_budget_paise,
            baseline_impact=round(baseline_impact, self.precision),
            projected_impact=round(projected_impact, self.precision),
            incremental_impact=round(incremental_impact, self.precision),
            impact_per_lakh=round(effective_rate_per_lakh, self.precision),
            marginal_impact_score=marginal_impact_score,
            diminishing_return_factor=diminishing_factor,
            calculation_version=self.calculation_version,
            component_breakdown=component_breakdown,
            weights_used=weights_used,
            allocation_context=allocation_context,
            engine_version=self.engine_version,
            input_schema=self.input_schema,
            dependency_versions=self.dependency_versions,
        )

    def calculate(
        self,
        project: Project,
        increment_paise: int = DEFAULT_MARGINAL_INCREMENT_PAISE,
        saturation_result: SaturationResult | None = None,
    ) -> MarginalImpactResult:
        """Contract compatibility alias delegating to calculate_marginal_impact.

        Maintains exact interface compatibility with Technical Contract Section 60.
        """
        return self.calculate_marginal_impact(
            project=project,
            saturation_result=saturation_result,
            increment_paise=increment_paise,
        )

    # -----------------------------------------------------------------------
    # Task E: Public Method - simulate_increment
    # -----------------------------------------------------------------------

    def simulate_increment(
        self,
        project: Project,
        saturation_result: SaturationResult | None = None,
        increment_paise: int | None = None,
    ) -> MarginalImpactResult | dict[str, MarginalImpactResult]:
        """Simulate incremental investment impact across standard or specified budget tiers.

        If increment_paise is None, simulates the 4 canonical tiers:
            - '1L':  ₹1 Lakh  (10,000,000 paise)
            - '2L':  ₹2 Lakh  (20,000,000 paise)
            - '5L':  ₹5 Lakh  (50,000,000 paise)
            - '10L': ₹10 Lakh (100,000,000 paise)

        Args:
            project: Project entity.
            saturation_result: Regional SaturationResult or None.
            increment_paise: Specific increment to simulate, or None for all tiers.

        Returns:
            Dictionary of tier simulation results, or single MarginalImpactResult.
        """
        if increment_paise is not None:
            return self.calculate_marginal_impact(
                project=project,
                saturation_result=saturation_result,
                increment_paise=increment_paise,
            )

        simulations: dict[str, MarginalImpactResult] = {}
        for tier_label, tier_paise in SIMULATION_TIERS.items():
            simulations[tier_label] = self.calculate_marginal_impact(
                project=project,
                saturation_result=saturation_result,
                increment_paise=tier_paise,
            )

        return simulations
