"""AllocateAI Decision Engine package (Member C).

Authoritative source: Software Contract v1.0 & Technical Contract v1.0.
Public package exports for all deterministic decision engine types, constants,
exceptions, utilities, and engine service interfaces.
"""

from backend.app.engine.constants import (
    API_VERSION,
    CALCULATION_VERSIONS,
    DEFAULT_MARGINAL_INCREMENT_PAISE,
    DNA_SCHEMA_VERSION,
    MARGINAL_CALCULATION_VERSION,
    OPTIMIZER_CALCULATION_VERSION,
    PAISE_PER_LAKH,
    PAISE_PER_RUPEE,
    PROJECT_SCHEMA_VERSION,
    RUPEES_PER_LAKH,
    SATURATION_CALCULATION_VERSION,
    SATURATION_HIGH_MAX,
    SATURATION_INTERPRETATION_BANDS,
    SATURATION_LOW_MAX,
    SATURATION_VERY_HIGH_MAX,
    SATURATION_VERY_LOW_MAX,
    SCORE_MAX,
    SCORE_MIN,
    WEIGHT_MAX,
    WEIGHT_MIN,
    WEIGHT_SUM_TARGET,
    WEIGHT_SUM_TOLERANCE,
    AllocationStatus,
    AuditEventType,
    ConfidenceLevel,
    DueDiligenceRisk,
    OptimizationStatus,
    ProjectSector,
    ProposalStatus,
    ReasonCode,
    VerificationStatus,
)
from backend.app.engine.constraints import ConstraintEngine
from backend.app.engine.exceptions import (
    BudgetValidationError,
    CalculationVersionError,
    ConstraintViolationError,
    DecisionEngineError,
    InvalidProjectDataError,
    WeightValidationError,
)
from backend.app.engine.marginal_impact import MarginalImpactEngine
from backend.app.engine.optimizer import AllocationOptimizer
from backend.app.engine.saturation import SaturationContext, SaturationEngine
from backend.app.engine.schemas import (
    Allocation,
    BeneficiaryProfile,
    Financials,
    Geography,
    ImpactDNA,
    ImpactMetric,
    MarginalImpactResult,
    OptimizationConstraints,
    OptimizationRequest,
    OptimizationResult,
    OptimizationWeights,
    Project,
    ProjectPerformanceUpdate,
    ReallocationRequest,
    ReallocationResult,
    SaturationResult,
)
from backend.app.engine.scoring import ScoringEngine
from backend.app.engine.utils import (
    clip_score,
    normalize_weights,
    safe_division,
    validate_budget,
    validate_calculation_version,
    validate_paise,
    validate_score,
    validate_weights,
)

__all__ = [
    # Constants & Enums
    "ProjectSector",
    "ReasonCode",
    "OptimizationStatus",
    "AllocationStatus",
    "VerificationStatus",
    "ConfidenceLevel",
    "DueDiligenceRisk",
    "ProposalStatus",
    "AuditEventType",
    "PROJECT_SCHEMA_VERSION",
    "DNA_SCHEMA_VERSION",
    "SATURATION_CALCULATION_VERSION",
    "MARGINAL_CALCULATION_VERSION",
    "OPTIMIZER_CALCULATION_VERSION",
    "API_VERSION",
    "CALCULATION_VERSIONS",
    "PAISE_PER_RUPEE",
    "RUPEES_PER_LAKH",
    "PAISE_PER_LAKH",
    "DEFAULT_MARGINAL_INCREMENT_PAISE",
    "SCORE_MIN",
    "SCORE_MAX",
    "WEIGHT_MIN",
    "WEIGHT_MAX",
    "WEIGHT_SUM_TARGET",
    "WEIGHT_SUM_TOLERANCE",
    "SATURATION_VERY_LOW_MAX",
    "SATURATION_LOW_MAX",
    "SATURATION_HIGH_MAX",
    "SATURATION_VERY_HIGH_MAX",
    "SATURATION_INTERPRETATION_BANDS",
    # Exceptions
    "DecisionEngineError",
    "ConstraintViolationError",
    "WeightValidationError",
    "InvalidProjectDataError",
    "BudgetValidationError",
    "CalculationVersionError",
    # Utilities
    "validate_score",
    "clip_score",
    "safe_division",
    "validate_paise",
    "validate_budget",
    "normalize_weights",
    "validate_weights",
    "validate_calculation_version",
    # Schemas
    "Geography",
    "BeneficiaryProfile",
    "Financials",
    "ImpactMetric",
    "ImpactDNA",
    "Project",
    "SaturationContext",
    "SaturationResult",
    "MarginalImpactResult",
    "OptimizationWeights",
    "OptimizationConstraints",
    "OptimizationRequest",
    "Allocation",
    "OptimizationResult",
    "ProjectPerformanceUpdate",
    "ReallocationRequest",
    "ReallocationResult",
    # Engine Interfaces
    "ScoringEngine",
    "SaturationEngine",
    "MarginalImpactEngine",
    "AllocationOptimizer",
    "ConstraintEngine",
]
